### ISSUE TITLE
Supervisorctl is missing on update

### ISSUE THREAD

**Issue by groblochon** [spiroid/cozy-apps#10]
When i update cozy-controller from 2.5.8, you need to install supervisor before :

`controller_1    | [2016-06-07 16:32:28:118] warn - controllers:applications | Can't restart the controller`
`controller_1    | [2016-06-07 16:32:28:118] warn - controllers:applications | Can't restart the controller`
`controller_1    | [2016-06-07 16:32:28:121] warn - controllers:applications | Error: Command failed: /bin/sh: 1: supervisorctl: not found`
`controller_1    |`
`controller_1    |     at ChildProcess.exithandler (child_process.js:658:15)`
`controller_1    |     at ChildProcess.emit (events.js:98:17)`
`controller_1    |     at maybeClose (child_process.js:766:16)`
`controller_1    |     at Process.ChildProcess._handle.onexit (child_process.js:833:5)`
`controller_1    | [2016-06-07 16:32:28:121] warn - controllers:applications | Error: Command failed: /bin/sh: 1: supervisorctl: not found`
`controller_1    |`
`controller_1    |     at ChildProcess.exithandler (child_process.js:658:15)`
`controller_1    |     at ChildProcess.emit (events.js:98:17)`
`controller_1    |     at maybeClose (child_process.js:766:16)`
`controller_1    |     at Process.ChildProcess._handle.onexit (child_process.js:833:5)`
`controller_1    | [2016-06-07 16:32:28:122] error - controllers:applications | The controller can't be restarted. You should configure the command in /etc/cozy/controller.json.`
`controller_1    | [2016-06-07 16:32:28:122] error - controllers:applications | The controller can't be restarted. You should configure the command in /etc/cozy/controller.json.`
`controller_1    | Sending error to client:`
`controller_1    | Error: Cannot update stack: The controller can't be restarted. You should configure the command in /etc/cozy/controller.json.`
`controller_1    |     at /usr/local/lib/node_modules/cozy-controller/build/server/controllers/applications.js:330:23`
`controller_1    |     at /usr/local/lib/node_modules/cozy-controller/build/server/controllers/applications.js:87:14`
`controller_1    |     at ChildProcess.exithandler (child_process.js:662:7)`
`controller_1    |     at ChildProcess.emit (events.js:98:17)`
`controller_1    |     at maybeClose (child_process.js:766:16)`
`controller_1    |     at Process.ChildProcess._handle.onexit (child_process.js:833:5)`

**Comment by spiroid** [comment]
thx for the bug report, i'il try to upgrade and see if i can reproduce the supervisorctl error
